version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "arena-infra"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-zjbkzyx9vhwj"
s3_prefix = "arena-infra"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
